WIDTH = 1500                        # Ancho de la ventana
HEIGHT = 900                        # Alto de la ventana
LENGTH_SQUARE = 20                  # Tamaño del lado del cuadrado que salta
LENGTH_TARGET = 10                  # Tamaño del lado del cuadrado que muestra donde soltaste el mouse
COLOR_SQUARE = (0, 0, 0)            # Color del cuadrado que salta
COLOR_TARGET = (255, 0, 0)          # Color del cuadrado que muestra donde soltaste el mouse
COLOR_LINE = (255, 0, 0)            # Color de la línea que muestra el vector Fuerza
COLOR_DRAGS = (70, 70, 70)          # Color de los inputs fricción y rebote
FPS = 500                           # FPS, el programa puede funcionar con menos FPS... pero irá más lenta
DATA_FONT_COLOR = (0, 0, 0)         # Color del texto
COLOR_WINDOW = (222, 236, 246)      # Color de la ventana
COLOR_PISO = (197, 107, 67)         # Color del piso de la simulación
ALTURA_PISO = 50                     # Altura del piso en pixeles
